// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request to create a new role.
public struct CreateRoleRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The `parent` parameter's value depends on the target resource for the
  /// request, namely
  /// [`projects`](https://cloud.google.com/iam/reference/rest/v1/projects.roles)
  /// or
  /// [`organizations`](https://cloud.google.com/iam/reference/rest/v1/organizations.roles).
  /// Each resource type's `parent` value format is described below:
  ///
  /// * [`projects.roles.create()`](https://cloud.google.com/iam/reference/rest/v1/projects.roles/create):
  ///   `projects/{PROJECT_ID}`. This method creates project-level
  ///   [custom
  ///   roles](https://cloud.google.com/iam/docs/understanding-custom-roles).
  ///   Example request URL:
  ///   `https://iam.googleapis.com/v1/projects/{PROJECT_ID}/roles`
  ///
  /// * [`organizations.roles.create()`](https://cloud.google.com/iam/reference/rest/v1/organizations.roles/create):
  ///   `organizations/{ORGANIZATION_ID}`. This method creates organization-level
  ///   [custom
  ///   roles](https://cloud.google.com/iam/docs/understanding-custom-roles).
  ///   Example request URL:
  ///   `https://iam.googleapis.com/v1/organizations/{ORGANIZATION_ID}/roles`
  ///
  /// Note: Wildcard (*) values are invalid; you must specify a complete project
  /// ID or organization ID.
  public var parent: Swift.String = Swift.String()

  /// The role ID to use for this role.
  ///
  /// A role ID may contain alphanumeric characters, underscores (`_`), and
  /// periods (`.`). It must contain a minimum of 3 characters and a maximum of
  /// 64 characters.
  public var roleId: Swift.String = Swift.String()

  /// The Role resource to create.
  public var role: Role? = nil

  /// Initialize a new instance of `CreateRoleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateRoleRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.iam.admin.v1.CreateRoleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
