// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request to get the definition of an existing role.
public struct GetRoleRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The `name` parameter's value depends on the target resource for the
  /// request, namely
  /// [`roles`](https://cloud.google.com/iam/reference/rest/v1/roles),
  /// [`projects`](https://cloud.google.com/iam/reference/rest/v1/projects.roles),
  /// or
  /// [`organizations`](https://cloud.google.com/iam/reference/rest/v1/organizations.roles).
  /// Each resource type's `name` value format is described below:
  ///
  /// * [`roles.get()`](https://cloud.google.com/iam/reference/rest/v1/roles/get): `roles/{ROLE_NAME}`.
  ///   This method returns results from all
  ///   [predefined
  ///   roles](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles)
  ///   in Cloud IAM. Example request URL:
  ///   `https://iam.googleapis.com/v1/roles/{ROLE_NAME}`
  ///
  /// * [`projects.roles.get()`](https://cloud.google.com/iam/reference/rest/v1/projects.roles/get):
  ///   `projects/{PROJECT_ID}/roles/{CUSTOM_ROLE_ID}`. This method returns only
  ///   [custom
  ///   roles](https://cloud.google.com/iam/docs/understanding-custom-roles) that
  ///   have been created at the project level. Example request URL:
  ///   `https://iam.googleapis.com/v1/projects/{PROJECT_ID}/roles/{CUSTOM_ROLE_ID}`
  ///
  /// * [`organizations.roles.get()`](https://cloud.google.com/iam/reference/rest/v1/organizations.roles/get):
  ///   `organizations/{ORGANIZATION_ID}/roles/{CUSTOM_ROLE_ID}`. This method
  ///   returns only [custom
  ///   roles](https://cloud.google.com/iam/docs/understanding-custom-roles) that
  ///   have been created at the organization level. Example request URL:
  ///   `https://iam.googleapis.com/v1/organizations/{ORGANIZATION_ID}/roles/{CUSTOM_ROLE_ID}`
  ///
  /// Note: Wildcard (*) values are invalid; you must specify a complete project
  /// ID or organization ID.
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `GetRoleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetRoleRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.GetRoleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
