// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleIAMV1
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class IAMLogging: IAMStub {
    let inner: any IAMStub
    let logger: Logger

    public init(_ inner: any IAMStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-iam-admin-v1"
      logger[metadataKey: "gcp.client.service"] = "iam"
      logger[metadataKey: "gcp.experimental.swift.client"] = "IAM"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listServiceAccounts(
      request: ListServiceAccountsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ListServiceAccountsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceAccounts",
        action: {
          (r: ListServiceAccountsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ListServiceAccountsResponse
          in
          return try await self.inner.listServiceAccounts(request: r, options: o)
        })
    }

    public func getServiceAccount(
      request: GetServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceAccount",
        action: {
          (r: GetServiceAccountRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccount
          in
          return try await self.inner.getServiceAccount(request: r, options: o)
        })
    }

    public func createServiceAccount(
      request: CreateServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceAccount",
        action: {
          (r: CreateServiceAccountRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccount
          in
          return try await self.inner.createServiceAccount(request: r, options: o)
        })
    }

    public func updateServiceAccount(
      request: ServiceAccount, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateServiceAccount",
        action: {
          (r: ServiceAccount, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccount
          in
          return try await self.inner.updateServiceAccount(request: r, options: o)
        })
    }

    public func patchServiceAccount(
      request: PatchServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "patchServiceAccount",
        action: {
          (r: PatchServiceAccountRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccount
          in
          return try await self.inner.patchServiceAccount(request: r, options: o)
        })
    }

    public func deleteServiceAccount(
      request: DeleteServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceAccount",
        action: {
          (r: DeleteServiceAccountRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteServiceAccount(request: r, options: o)
        })
    }

    public func undeleteServiceAccount(
      request: UndeleteServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.UndeleteServiceAccountResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteServiceAccount",
        action: {
          (r: UndeleteServiceAccountRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.UndeleteServiceAccountResponse
          in
          return try await self.inner.undeleteServiceAccount(request: r, options: o)
        })
    }

    public func enableServiceAccount(
      request: EnableServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "enableServiceAccount",
        action: {
          (r: EnableServiceAccountRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.enableServiceAccount(request: r, options: o)
        })
    }

    public func disableServiceAccount(
      request: DisableServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "disableServiceAccount",
        action: {
          (r: DisableServiceAccountRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.disableServiceAccount(request: r, options: o)
        })
    }

    public func listServiceAccountKeys(
      request: ListServiceAccountKeysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ListServiceAccountKeysResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceAccountKeys",
        action: {
          (r: ListServiceAccountKeysRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ListServiceAccountKeysResponse
          in
          return try await self.inner.listServiceAccountKeys(request: r, options: o)
        })
    }

    public func getServiceAccountKey(
      request: GetServiceAccountKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccountKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceAccountKey",
        action: {
          (r: GetServiceAccountKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccountKey
          in
          return try await self.inner.getServiceAccountKey(request: r, options: o)
        })
    }

    public func createServiceAccountKey(
      request: CreateServiceAccountKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccountKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceAccountKey",
        action: {
          (r: CreateServiceAccountKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccountKey
          in
          return try await self.inner.createServiceAccountKey(request: r, options: o)
        })
    }

    public func uploadServiceAccountKey(
      request: UploadServiceAccountKeyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccountKey {
      try await self._intercept(
        request: request,
        options: options,
        name: "uploadServiceAccountKey",
        action: {
          (r: UploadServiceAccountKeyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ServiceAccountKey
          in
          return try await self.inner.uploadServiceAccountKey(request: r, options: o)
        })
    }

    public func deleteServiceAccountKey(
      request: DeleteServiceAccountKeyRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteServiceAccountKey",
        action: {
          (r: DeleteServiceAccountKeyRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteServiceAccountKey(request: r, options: o)
        })
    }

    public func disableServiceAccountKey(
      request: DisableServiceAccountKeyRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "disableServiceAccountKey",
        action: {
          (r: DisableServiceAccountKeyRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.disableServiceAccountKey(request: r, options: o)
        })
    }

    public func enableServiceAccountKey(
      request: EnableServiceAccountKeyRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "enableServiceAccountKey",
        action: {
          (r: EnableServiceAccountKeyRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.enableServiceAccountKey(request: r, options: o)
        })
    }

    public func signBlob(
      request: SignBlobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.SignBlobResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "signBlob",
        action: {
          (r: SignBlobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.SignBlobResponse
          in
          return try await self.inner.signBlob(request: r, options: o)
        })
    }

    public func signJwt(
      request: SignJwtRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.SignJwtResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "signJwt",
        action: {
          (r: SignJwtRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.SignJwtResponse
          in
          return try await self.inner.signJwt(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func queryGrantableRoles(
      request: QueryGrantableRolesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.QueryGrantableRolesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryGrantableRoles",
        action: {
          (r: QueryGrantableRolesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.QueryGrantableRolesResponse
          in
          return try await self.inner.queryGrantableRoles(request: r, options: o)
        })
    }

    public func listRoles(
      request: ListRolesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ListRolesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRoles",
        action: {
          (r: ListRolesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.ListRolesResponse
          in
          return try await self.inner.listRoles(request: r, options: o)
        })
    }

    public func getRole(
      request: GetRoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRole",
        action: {
          (r: GetRoleRequest, o: GoogleGax.RequestOptions) async throws -> GoogleIAMAdminV1.Role
          in
          return try await self.inner.getRole(request: r, options: o)
        })
    }

    public func createRole(
      request: CreateRoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRole",
        action: {
          (r: CreateRoleRequest, o: GoogleGax.RequestOptions) async throws -> GoogleIAMAdminV1.Role
          in
          return try await self.inner.createRole(request: r, options: o)
        })
    }

    public func updateRole(
      request: UpdateRoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRole",
        action: {
          (r: UpdateRoleRequest, o: GoogleGax.RequestOptions) async throws -> GoogleIAMAdminV1.Role
          in
          return try await self.inner.updateRole(request: r, options: o)
        })
    }

    public func deleteRole(
      request: DeleteRoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRole",
        action: {
          (r: DeleteRoleRequest, o: GoogleGax.RequestOptions) async throws -> GoogleIAMAdminV1.Role
          in
          return try await self.inner.deleteRole(request: r, options: o)
        })
    }

    public func undeleteRole(
      request: UndeleteRoleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteRole",
        action: {
          (r: UndeleteRoleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.Role
          in
          return try await self.inner.undeleteRole(request: r, options: o)
        })
    }

    public func queryTestablePermissions(
      request: QueryTestablePermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.QueryTestablePermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryTestablePermissions",
        action: {
          (r: QueryTestablePermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.QueryTestablePermissionsResponse
          in
          return try await self.inner.queryTestablePermissions(request: r, options: o)
        })
    }

    public func queryAuditableServices(
      request: QueryAuditableServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.QueryAuditableServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryAuditableServices",
        action: {
          (r: QueryAuditableServicesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.QueryAuditableServicesResponse
          in
          return try await self.inner.queryAuditableServices(request: r, options: o)
        })
    }

    public func lintPolicy(
      request: LintPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.LintPolicyResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "lintPolicy",
        action: {
          (r: LintPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMAdminV1.LintPolicyResponse
          in
          return try await self.inner.lintPolicy(request: r, options: o)
        })
    }
  }
}
