// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleCloudGax

extension Clients {
  protocol IAMStub: Sendable {
    func listServiceAccounts(
      request: ListServiceAccountsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ListServiceAccountsResponse

    func getServiceAccount(
      request: GetServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount

    func createServiceAccount(
      request: CreateServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount

    func updateServiceAccount(
      request: ServiceAccount, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount

    func patchServiceAccount(
      request: PatchServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccount

    func deleteServiceAccount(
      request: DeleteServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func undeleteServiceAccount(
      request: UndeleteServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.UndeleteServiceAccountResponse

    func enableServiceAccount(
      request: EnableServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func disableServiceAccount(
      request: DisableServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listServiceAccountKeys(
      request: ListServiceAccountKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ListServiceAccountKeysResponse

    func getServiceAccountKey(
      request: GetServiceAccountKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccountKey

    func createServiceAccountKey(
      request: CreateServiceAccountKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccountKey

    func uploadServiceAccountKey(
      request: UploadServiceAccountKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ServiceAccountKey

    func deleteServiceAccountKey(
      request: DeleteServiceAccountKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func disableServiceAccountKey(
      request: DisableServiceAccountKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func enableServiceAccountKey(
      request: EnableServiceAccountKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func signBlob(
      request: SignBlobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.SignBlobResponse

    func signJwt(
      request: SignJwtRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.SignJwtResponse

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func queryGrantableRoles(
      request: QueryGrantableRolesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.QueryGrantableRolesResponse

    func listRoles(
      request: ListRolesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.ListRolesResponse

    func getRole(
      request: GetRoleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role

    func createRole(
      request: CreateRoleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role

    func updateRole(
      request: UpdateRoleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role

    func deleteRole(
      request: DeleteRoleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role

    func undeleteRole(
      request: UndeleteRoleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.Role

    func queryTestablePermissions(
      request: QueryTestablePermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.QueryTestablePermissionsResponse

    func queryAuditableServices(
      request: QueryAuditableServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.QueryAuditableServicesResponse

    func lintPolicy(
      request: LintPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMAdminV1.LintPolicyResponse
  }
}
