// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Structured response of a single validation unit.
public struct LintResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The validation unit level.
  public var level: LintResult.Level = LintResult.Level()

  /// The validation unit name, for instance
  /// "lintValidationUnits/ConditionComplexityCheck".
  public var validationUnitName: Swift.String = Swift.String()

  /// The validation unit severity.
  public var severity: LintResult.Severity = LintResult.Severity()

  /// The name of the field for which this lint result is about.
  ///
  /// For nested messages `field_name` consists of names of the embedded fields
  /// separated by period character. The top-level qualifier is the input object
  /// to lint in the request. For example, the `field_name` value
  /// `condition.expression` identifies a lint result for the `expression` field
  /// of the provided condition.
  public var fieldName: Swift.String = Swift.String()

  /// 0-based character position of problematic construct within the object
  /// identified by `field_name`. Currently, this is populated only for condition
  /// expression.
  public var locationOffset: Swift.Int32 = Swift.Int32()

  /// Human readable debug message associated with the issue.
  public var debugMessage: Swift.String = Swift.String()

  /// Initialize a new instance of `LintResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LintResult().with { $0.level = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible Level values of a validation unit corresponding to its domain
  /// of discourse.
  public enum Level: Codable, Equatable, Sendable {
    /// Level is unspecified.
    case unspecified
    /// A validation unit which operates on an individual condition within a
    /// binding.
    case condition
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .condition: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LEVEL_UNSPECIFIED"
      case .condition: return "CONDITION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LEVEL_UNSPECIFIED": self = .unspecified
      case "CONDITION": self = .condition
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 3: self = .condition
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .condition: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible Severity values of an issued result.
  public enum Severity: Codable, Equatable, Sendable {
    /// Severity is unspecified.
    case unspecified
    /// A validation unit returns an error only for critical issues. If an
    /// attempt is made to set the problematic policy without rectifying the
    /// critical issue, it causes the `setPolicy` operation to fail.
    case error
    /// Any issue which is severe enough but does not cause an error.
    /// For example, suspicious constructs in the input object will not
    /// necessarily fail `setPolicy`, but there is a high likelihood that they
    /// won't behave as expected during policy evaluation in `checkPolicy`.
    /// This includes the following common scenarios:
    ///
    /// - Unsatisfiable condition: Expired timestamp in date/time condition.
    /// - Ineffective condition: Condition on a <principal, role> pair which is
    ///   granted unconditionally in another binding of the same policy.
    case warning
    /// Reserved for the issues that are not severe as `ERROR`/`WARNING`, but
    /// need special handling. For instance, messages about skipped validation
    /// units are issued as `NOTICE`.
    case notice
    /// Any informative statement which is not severe enough to raise
    /// `ERROR`/`WARNING`/`NOTICE`, like auto-correction recommendations on the
    /// input content. Note that current version of the linter does not utilize
    /// `INFO`.
    case info
    /// Deprecated severity level.
    case deprecated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .error: return 1
      case .warning: return 2
      case .notice: return 3
      case .info: return 4
      case .deprecated: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEVERITY_UNSPECIFIED"
      case .error: return "ERROR"
      case .warning: return "WARNING"
      case .notice: return "NOTICE"
      case .info: return "INFO"
      case .deprecated: return "DEPRECATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEVERITY_UNSPECIFIED": self = .unspecified
      case "ERROR": self = .error
      case "WARNING": self = .warning
      case "NOTICE": self = .notice
      case "INFO": self = .info
      case "DEPRECATED": self = .deprecated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .error
      case 2: self = .warning
      case 3: self = .notice
      case 4: self = .info
      case 5: self = .deprecated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .error: return try container.encode(1)
      case .warning: return try container.encode(2)
      case .notice: return try container.encode(3)
      case .info: return try container.encode(4)
      case .deprecated: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.LintResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
