// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// The request to lint a Cloud IAM policy object.
public struct LintPolicyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The full resource name of the policy this lint request is about.
  ///
  /// The name follows the Google Cloud Platform (GCP) resource format.
  /// For example, a GCP project with ID `my-project` will be named
  /// `//cloudresourcemanager.googleapis.com/projects/my-project`.
  ///
  /// The resource name is not used to read the policy instance from the Cloud
  /// IAM database. The candidate policy for lint has to be provided in the same
  /// request object.
  public var fullResourceName: Swift.String = Swift.String()

  /// Required. The Cloud IAM object to be linted.
  public var lintObject: OneOf_LintObject? = nil

  /// Initialize a new instance of `LintPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LintPolicyRequest().with { $0.fullResourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case fullResourceName = "fullResourceName"
    case condition = "condition"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.fullResourceName = try container.decode(Swift.String.self, forKey: .fullResourceName)

    var lintObject: OneOf_LintObject? = nil
    let lintObjectCheckAndSet = {
      if lintObject != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'lintObject'"))
      }
      lintObject = $0
    }
    if let condition = try container.decodeIfPresent(GoogleType.Expr?.self, forKey: .condition) {
      try lintObjectCheckAndSet(.condition(condition))
    }
    self.lintObject = lintObject
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.fullResourceName, forKey: .fullResourceName)

    if let choice = self.lintObject {
      switch choice {
      case .condition(let value):
        try container.encode(value, forKey: .condition)
      }
    }
  }

  /// Required. The Cloud IAM object to be linted.
  public enum OneOf_LintObject: Codable, Equatable, Sendable {
    /// [google.iam.v1.Binding.condition] [google.iam.v1.Binding.condition] object to be linted.
    indirect case condition(GoogleType.Expr?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.iam.admin.v1.LintPolicyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
