// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The service account list request.
public struct ListServiceAccountsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the project associated with the service
  /// accounts, such as `projects/my-project-123`.
  public var name: Swift.String = Swift.String()

  /// Optional limit on the number of service accounts to include in the
  /// response. Further accounts can subsequently be obtained by including the
  /// [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]
  /// in a subsequent request.
  ///
  /// The default is 20, and the maximum is 100.
  ///
  /// [google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]: <doc:ListServiceAccountsResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional pagination token returned in an earlier
  /// [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token].
  ///
  /// [google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]: <doc:ListServiceAccountsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListServiceAccountsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListServiceAccountsRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.ListServiceAccountsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
