// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request to get all roles defined under a resource.
public struct ListRolesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The `parent` parameter's value depends on the target resource for the
  /// request, namely
  /// [`roles`](https://cloud.google.com/iam/reference/rest/v1/roles),
  /// [`projects`](https://cloud.google.com/iam/reference/rest/v1/projects.roles),
  /// or
  /// [`organizations`](https://cloud.google.com/iam/reference/rest/v1/organizations.roles).
  /// Each resource type's `parent` value format is described below:
  ///
  /// * [`roles.list()`](https://cloud.google.com/iam/reference/rest/v1/roles/list): An empty string.
  ///   This method doesn't require a resource; it simply returns all
  ///   [predefined
  ///   roles](https://cloud.google.com/iam/docs/understanding-roles#predefined_roles)
  ///   in Cloud IAM. Example request URL: `https://iam.googleapis.com/v1/roles`
  ///
  /// * [`projects.roles.list()`](https://cloud.google.com/iam/reference/rest/v1/projects.roles/list):
  ///   `projects/{PROJECT_ID}`. This method lists all project-level
  ///   [custom
  ///   roles](https://cloud.google.com/iam/docs/understanding-custom-roles).
  ///   Example request URL:
  ///   `https://iam.googleapis.com/v1/projects/{PROJECT_ID}/roles`
  ///
  /// * [`organizations.roles.list()`](https://cloud.google.com/iam/reference/rest/v1/organizations.roles/list):
  ///   `organizations/{ORGANIZATION_ID}`. This method lists all
  ///   organization-level [custom
  ///   roles](https://cloud.google.com/iam/docs/understanding-custom-roles).
  ///   Example request URL:
  ///   `https://iam.googleapis.com/v1/organizations/{ORGANIZATION_ID}/roles`
  ///
  /// Note: Wildcard (*) values are invalid; you must specify a complete project
  /// ID or organization ID.
  public var parent: Swift.String = Swift.String()

  /// Optional limit on the number of roles to include in the response.
  ///
  /// The default is 300, and the maximum is 1,000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional pagination token returned in an earlier ListRolesResponse.
  public var pageToken: Swift.String = Swift.String()

  /// Optional view for the returned Role objects. When `FULL` is specified,
  /// the `includedPermissions` field is returned, which includes a list of all
  /// permissions in the role. The default value is `BASIC`, which does not
  /// return the `includedPermissions` field.
  public var view: RoleView = RoleView()

  /// Include Roles that have been deleted.
  public var showDeleted: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListRolesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRolesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.iam.admin.v1.ListRolesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
