// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A permission which can be included by a role.
public struct Permission: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of this Permission.
  public var name: Swift.String = Swift.String()

  /// The title of this Permission.
  public var title: Swift.String = Swift.String()

  /// A brief description of what this Permission is used for.
  /// This permission can ONLY be used in predefined roles.
  public var description: Swift.String = Swift.String()

  @available(*, deprecated)
  public var onlyInPredefinedRoles: Swift.Bool = Swift.Bool()

  /// The current launch stage of the permission.
  public var stage: Permission.PermissionLaunchStage = Permission.PermissionLaunchStage()

  /// The current custom role support level.
  public var customRolesSupportLevel: Permission.CustomRolesSupportLevel =
    Permission.CustomRolesSupportLevel()

  /// The service API associated with the permission is not enabled.
  public var apiDisabled: Swift.Bool = Swift.Bool()

  /// The preferred name for this permission. If present, then this permission is
  /// an alias of, and equivalent to, the listed primary_permission.
  public var primaryPermission: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Permission`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Permission().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let title = CodingKeys(stringValue: "title")
    static let description = CodingKeys(stringValue: "description")
    static let onlyInPredefinedRoles = CodingKeys(stringValue: "onlyInPredefinedRoles")
    static let stage = CodingKeys(stringValue: "stage")
    static let customRolesSupportLevel = CodingKeys(stringValue: "customRolesSupportLevel")
    static let apiDisabled = CodingKeys(stringValue: "apiDisabled")
    static let primaryPermission = CodingKeys(stringValue: "primaryPermission")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "title",
      "description",
      "onlyInPredefinedRoles",
      "stage",
      "customRolesSupportLevel",
      "apiDisabled",
      "primaryPermission",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
      self.title = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .onlyInPredefinedRoles) {
      self.onlyInPredefinedRoles = value
    }
    if let value = try container.decodeIfPresent(
      Permission.PermissionLaunchStage.self, forKey: .stage)
    {
      self.stage = value
    }
    if let value = try container.decodeIfPresent(
      Permission.CustomRolesSupportLevel.self, forKey: .customRolesSupportLevel)
    {
      self.customRolesSupportLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .apiDisabled) {
      self.apiDisabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primaryPermission) {
      self.primaryPermission = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.onlyInPredefinedRoles, forKey: .onlyInPredefinedRoles)
    try container.encode(self.stage, forKey: .stage)
    try container.encode(self.customRolesSupportLevel, forKey: .customRolesSupportLevel)
    try container.encode(self.apiDisabled, forKey: .apiDisabled)
    try container.encode(self.primaryPermission, forKey: .primaryPermission)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A stage representing a permission's lifecycle phase.
  public enum PermissionLaunchStage: Codable, Equatable, Sendable {
    /// The permission is currently in an alpha phase.
    case alpha
    /// The permission is currently in a beta phase.
    case beta
    /// The permission is generally available.
    case ga
    /// The permission is being deprecated.
    case deprecated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .alpha
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .alpha: return 0
      case .beta: return 1
      case .ga: return 2
      case .deprecated: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .alpha: return "ALPHA"
      case .beta: return "BETA"
      case .ga: return "GA"
      case .deprecated: return "DEPRECATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PermissionLaunchStage/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ALPHA": self = .alpha
      case "BETA": self = .beta
      case "GA": self = .ga
      case "DEPRECATED": self = .deprecated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PermissionLaunchStage/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .alpha
      case 1: self = .beta
      case 2: self = .ga
      case 3: self = .deprecated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .alpha: return try container.encode("ALPHA")
      case .beta: return try container.encode("BETA")
      case .ga: return try container.encode("GA")
      case .deprecated: return try container.encode("DEPRECATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The state of the permission with regards to custom roles.
  public enum CustomRolesSupportLevel: Codable, Equatable, Sendable {
    /// Default state. Permission is fully supported for custom role use.
    case supported
    /// Permission is being tested to check custom role compatibility.
    case testing
    /// Permission is not supported for custom role use.
    case notSupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .supported
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .supported: return 0
      case .testing: return 1
      case .notSupported: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .supported: return "SUPPORTED"
      case .testing: return "TESTING"
      case .notSupported: return "NOT_SUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CustomRolesSupportLevel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SUPPORTED": self = .supported
      case "TESTING": self = .testing
      case "NOT_SUPPORTED": self = .notSupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CustomRolesSupportLevel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .supported
      case 1: self = .testing
      case 2: self = .notSupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .supported: return try container.encode("SUPPORTED")
      case .testing: return try container.encode("TESTING")
      case .notSupported: return try container.encode("NOT_SUPPORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.Permission"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
