// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A permission which can be included by a role.
public struct Permission: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of this Permission.
  public var name: Swift.String = Swift.String()

  /// The title of this Permission.
  public var title: Swift.String = Swift.String()

  /// A brief description of what this Permission is used for.
  /// This permission can ONLY be used in predefined roles.
  public var description: Swift.String = Swift.String()

  @available(*, deprecated)
  public var onlyInPredefinedRoles: Swift.Bool = Swift.Bool()

  /// The current launch stage of the permission.
  public var stage: Permission.PermissionLaunchStage = Permission.PermissionLaunchStage()

  /// The current custom role support level.
  public var customRolesSupportLevel: Permission.CustomRolesSupportLevel =
    Permission.CustomRolesSupportLevel()

  /// The service API associated with the permission is not enabled.
  public var apiDisabled: Swift.Bool = Swift.Bool()

  /// The preferred name for this permission. If present, then this permission is
  /// an alias of, and equivalent to, the listed primary_permission.
  public var primaryPermission: Swift.String = Swift.String()

  /// Initialize a new instance of `Permission`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Permission().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A stage representing a permission's lifecycle phase.
  public enum PermissionLaunchStage: Codable, Equatable, Sendable {
    /// The permission is currently in an alpha phase.
    case alpha
    /// The permission is currently in a beta phase.
    case beta
    /// The permission is generally available.
    case ga
    /// The permission is being deprecated.
    case deprecated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .alpha
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .alpha: return 0
      case .beta: return 1
      case .ga: return 2
      case .deprecated: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .alpha: return "ALPHA"
      case .beta: return "BETA"
      case .ga: return "GA"
      case .deprecated: return "DEPRECATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ALPHA": self = .alpha
      case "BETA": self = .beta
      case "GA": self = .ga
      case "DEPRECATED": self = .deprecated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .alpha
      case 1: self = .beta
      case 2: self = .ga
      case 3: self = .deprecated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .alpha: return try container.encode(0)
      case .beta: return try container.encode(1)
      case .ga: return try container.encode(2)
      case .deprecated: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The state of the permission with regards to custom roles.
  public enum CustomRolesSupportLevel: Codable, Equatable, Sendable {
    /// Default state. Permission is fully supported for custom role use.
    case supported
    /// Permission is being tested to check custom role compatibility.
    case testing
    /// Permission is not supported for custom role use.
    case notSupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .supported
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .supported: return 0
      case .testing: return 1
      case .notSupported: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .supported: return "SUPPORTED"
      case .testing: return "TESTING"
      case .notSupported: return "NOT_SUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SUPPORTED": self = .supported
      case "TESTING": self = .testing
      case "NOT_SUPPORTED": self = .notSupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .supported
      case 1: self = .testing
      case 2: self = .notSupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .supported: return try container.encode(0)
      case .testing: return try container.encode(1)
      case .notSupported: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.Permission"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
