// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A role in the Identity and Access Management API.
public struct Role: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the role.
  ///
  /// When Role is used in CreateRole, the role name must not be set.
  ///
  /// When Role is used in output and other input such as UpdateRole, the role
  /// name is the complete path, e.g., roles/logging.viewer for predefined roles
  /// and organizations/{ORGANIZATION_ID}/roles/logging.viewer for custom roles.
  public var name: Swift.String = Swift.String()

  /// Optional. A human-readable title for the role.  Typically this
  /// is limited to 100 UTF-8 bytes.
  public var title: Swift.String = Swift.String()

  /// Optional. A human-readable description for the role.
  public var description: Swift.String = Swift.String()

  /// The names of the permissions this role grants when bound in an IAM policy.
  public var includedPermissions: [Swift.String] = []

  /// The current launch stage of the role. If the `ALPHA` launch stage has been
  /// selected for a role, the `stage` field will not be included in the
  /// returned definition for the role.
  public var stage: Role.RoleLaunchStage = Role.RoleLaunchStage()

  /// Used to perform a consistent read-modify-write.
  public var etag: Foundation.Data = Foundation.Data()

  /// The current deleted state of the role. This field is read only.
  /// It will be ignored in calls to CreateRole and UpdateRole.
  public var deleted: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Role`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Role().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A stage representing a role's lifecycle phase.
  public enum RoleLaunchStage: Codable, Equatable, Sendable {
    /// The user has indicated this role is currently in an Alpha phase. If this
    /// launch stage is selected, the `stage` field will not be included when
    /// requesting the definition for a given role.
    case alpha
    /// The user has indicated this role is currently in a Beta phase.
    case beta
    /// The user has indicated this role is generally available.
    case ga
    /// The user has indicated this role is being deprecated.
    case deprecated
    /// This role is disabled and will not contribute permissions to any
    /// principals it is granted to in policies.
    case disabled
    /// The user has indicated this role is currently in an EAP phase.
    case eap
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .alpha
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .alpha: return 0
      case .beta: return 1
      case .ga: return 2
      case .deprecated: return 4
      case .disabled: return 5
      case .eap: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .alpha: return "ALPHA"
      case .beta: return "BETA"
      case .ga: return "GA"
      case .deprecated: return "DEPRECATED"
      case .disabled: return "DISABLED"
      case .eap: return "EAP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RoleLaunchStage/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ALPHA": self = .alpha
      case "BETA": self = .beta
      case "GA": self = .ga
      case "DEPRECATED": self = .deprecated
      case "DISABLED": self = .disabled
      case "EAP": self = .eap
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RoleLaunchStage/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .alpha
      case 1: self = .beta
      case 2: self = .ga
      case 4: self = .deprecated
      case 5: self = .disabled
      case 6: self = .eap
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .alpha: return try container.encode(0)
      case .beta: return try container.encode(1)
      case .ga: return try container.encode(2)
      case .deprecated: return try container.encode(4)
      case .disabled: return try container.encode(5)
      case .eap: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.Role"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
