// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a service account key.
///
/// A service account has two sets of key-pairs: user-managed, and
/// system-managed.
///
/// User-managed key-pairs can be created and deleted by users.  Users are
/// responsible for rotating these keys periodically to ensure security of
/// their service accounts.  Users retain the private key of these key-pairs,
/// and Google retains ONLY the public key.
///
/// System-managed keys are automatically rotated by Google, and are used for
/// signing for a maximum of two weeks. The rotation process is probabilistic,
/// and usage of the new key will gradually ramp up and down over the key's
/// lifetime.
///
/// If you cache the public key set for a service account, we recommend that you
/// update the cache every 15 minutes. User-managed keys can be added and removed
/// at any time, so it is important to update the cache frequently. For
/// Google-managed keys, Google will publish a key at least 6 hours before it is
/// first used for signing and will keep publishing it for at least 6 hours after
/// it was last used for signing.
///
/// Public keys for all service accounts are also published at the OAuth2
/// Service Account API.
public struct ServiceAccountKey: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the service account key in the following format
  /// `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}/keys/{key}`.
  public var name: Swift.String = Swift.String()

  /// The output format for the private key.
  /// Only provided in `CreateServiceAccountKey` responses, not
  /// in `GetServiceAccountKey` or `ListServiceAccountKey` responses.
  ///
  /// Google never exposes system-managed private keys, and never retains
  /// user-managed private keys.
  public var privateKeyType: ServiceAccountPrivateKeyType = ServiceAccountPrivateKeyType()

  /// Specifies the algorithm (and possibly key size) for the key.
  public var keyAlgorithm: ServiceAccountKeyAlgorithm = ServiceAccountKeyAlgorithm()

  /// The private key data. Only provided in `CreateServiceAccountKey`
  /// responses. Make sure to keep the private key data secure because it
  /// allows for the assertion of the service account identity.
  /// When base64 decoded, the private key data can be used to authenticate with
  /// Google API client libraries and with
  /// <a href="/sdk/gcloud/reference/auth/activate-service-account">gcloud
  /// auth activate-service-account</a>.
  public var privateKeyData: Foundation.Data = Foundation.Data()

  /// The public key data. Only provided in `GetServiceAccountKey` responses.
  public var publicKeyData: Foundation.Data = Foundation.Data()

  /// The key can be used after this timestamp.
  public var validAfterTime: GoogleWKT.Timestamp? = nil

  /// The key can be used before this timestamp.
  /// For system-managed key pairs, this timestamp is the end time for the
  /// private key signing operation. The public key could still be used
  /// for verification for a few hours after this time.
  public var validBeforeTime: GoogleWKT.Timestamp? = nil

  /// The key origin.
  public var keyOrigin: ServiceAccountKeyOrigin = ServiceAccountKeyOrigin()

  /// The key type.
  public var keyType: ListServiceAccountKeysRequest.KeyType =
    ListServiceAccountKeysRequest.KeyType()

  /// The key status.
  public var disabled: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceAccountKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceAccountKey().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let privateKeyType = CodingKeys(stringValue: "privateKeyType")
    static let keyAlgorithm = CodingKeys(stringValue: "keyAlgorithm")
    static let privateKeyData = CodingKeys(stringValue: "privateKeyData")
    static let publicKeyData = CodingKeys(stringValue: "publicKeyData")
    static let validAfterTime = CodingKeys(stringValue: "validAfterTime")
    static let validBeforeTime = CodingKeys(stringValue: "validBeforeTime")
    static let keyOrigin = CodingKeys(stringValue: "keyOrigin")
    static let keyType = CodingKeys(stringValue: "keyType")
    static let disabled = CodingKeys(stringValue: "disabled")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "privateKeyType",
      "keyAlgorithm",
      "privateKeyData",
      "publicKeyData",
      "validAfterTime",
      "validBeforeTime",
      "keyOrigin",
      "keyType",
      "disabled",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      ServiceAccountPrivateKeyType.self, forKey: .privateKeyType)
    {
      self.privateKeyType = value
    }
    if let value = try container.decodeIfPresent(
      ServiceAccountKeyAlgorithm.self, forKey: .keyAlgorithm)
    {
      self.keyAlgorithm = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .privateKeyData) {
      self.privateKeyData = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .publicKeyData) {
      self.publicKeyData = value
    }
    self.validAfterTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .validAfterTime)
    self.validBeforeTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .validBeforeTime)
    if let value = try container.decodeIfPresent(ServiceAccountKeyOrigin.self, forKey: .keyOrigin) {
      self.keyOrigin = value
    }
    if let value = try container.decodeIfPresent(
      ListServiceAccountKeysRequest.KeyType.self, forKey: .keyType)
    {
      self.keyType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
      self.disabled = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.privateKeyType, forKey: .privateKeyType)
    try container.encode(self.keyAlgorithm, forKey: .keyAlgorithm)
    try container.encode(self.privateKeyData, forKey: .privateKeyData)
    try container.encode(self.publicKeyData, forKey: .publicKeyData)
    try container.encodeIfPresent(self.validAfterTime, forKey: .validAfterTime)
    try container.encodeIfPresent(self.validBeforeTime, forKey: .validBeforeTime)
    try container.encode(self.keyOrigin, forKey: .keyOrigin)
    try container.encode(self.keyType, forKey: .keyType)
    try container.encode(self.disabled, forKey: .disabled)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.admin.v1.ServiceAccountKey"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
