// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Supported public key output formats.
public enum ServiceAccountPublicKeyType: Codable, Equatable, Sendable {
  /// Do not return the public key.
  case typeNone
  /// X509 PEM format.
  case typeX509PemFile
  /// Raw public key.
  case typeRawPublicKey
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .typeNone
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .typeNone: return 0
    case .typeX509PemFile: return 1
    case .typeRawPublicKey: return 2
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .typeNone: return "TYPE_NONE"
    case .typeX509PemFile: return "TYPE_X509_PEM_FILE"
    case .typeRawPublicKey: return "TYPE_RAW_PUBLIC_KEY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ServiceAccountPublicKeyType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "TYPE_NONE": self = .typeNone
    case "TYPE_X509_PEM_FILE": self = .typeX509PemFile
    case "TYPE_RAW_PUBLIC_KEY": self = .typeRawPublicKey
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ServiceAccountPublicKeyType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .typeNone
    case 1: self = .typeX509PemFile
    case 2: self = .typeRawPublicKey
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .typeNone: return try container.encode(0)
    case .typeX509PemFile: return try container.encode(1)
    case .typeRawPublicKey: return try container.encode(2)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
